In [1]:
import pandas as pd

In [4]:
df = pd.read_csv("spotify_millsongdata.csv")

In [5]:
df.head()

,artist,song,link,text
0,ABBA,Ahe's My Kind Of Girl,/a/abba/ahes+my+kind+of+girl_20598417.html,"Look at her face, it's a wonderful face \r\nA..."
1,ABBA,"Andante, Andante",/a/abba/andante+andante_20002708.html,"Take it easy with me, please \r\nTouch me gen..."
2,ABBA,As Good As New,/a/abba/as+good+as+new_20003033.html,I'll never know why I had to go \r\nWhy I had...
3,ABBA,Bang,/a/abba/bang_20598415.html,Making somebody happy is a question of give an...
4,ABBA,Bang-A-Boomerang,/a/abba/bang+a+boomerang_20002668.html,Making somebody happy is a question of give an...

In [6]:
df.tail()

,artist,song,link,text
57645,Ziggy Marley,Good Old Days,/z/ziggy+marley/good+old+days_10198588.html,Irie days come on play \r\nLet the angels fly...
57646,Ziggy Marley,Hand To Mouth,/z/ziggy+marley/hand+to+mouth_20531167.html,Power to the workers \r\nMore power \r\nPowe...
57647,Zwan,Come With Me,/z/zwan/come+with+me_20148981.html,all you need \r\nis something i'll believe \...
57648,Zwan,Desire,/z/zwan/desire_20148986.html,northern star \r\nam i frightened \r\nwhere ...
57649,Zwan,Heartsong,/z/zwan/heartsong_20148991.html,come in \r\nmake yourself at home \r\ni'm a ...

In [8]:
df.shape

(57650, 4)

In [10]:
df.isnull().sum()

artist    0
song      0
link      0
text      0
dtype: int64

In [12]:
df = df.drop('link', axis=1).reset_index(drop=True)

In [13]:
df.head()

,artist,song,text
0,ABBA,Ahe's My Kind Of Girl,"Look at her face, it's a wonderful face \r\nA..."
1,ABBA,"Andante, Andante","Take it easy with me, please \r\nTouch me gen..."
2,ABBA,As Good As New,I'll never know why I had to go \r\nWhy I had...
3,ABBA,Bang,Making somebody happy is a question of give an...
4,ABBA,Bang-A-Boomerang,Making somebody happy is a question of give an...

In [14]:
df['text'][0]

"Look at her face, it's a wonderful face  \r\nAnd it means something special to me  \r\nLook at the way that she smiles when she sees me  \r\nHow lucky can one fellow be?  \r\n  \r\nShe's just my kind of girl, she makes me feel fine  \r\nWho could ever believe that she could be mine?  \r\nShe's just my kind of girl, without her I'm blue  \r\nAnd if she ever leaves me what could I do, what could I do?  \r\n  \r\nAnd when we go for a walk in the park  \r\nAnd she holds me and squeezes my hand  \r\nWe'll go on walking for hours and talking  \r\nAbout all the things that we plan  \r\n  \r\nShe's just my kind of girl, she makes me feel fine  \r\nWho could ever believe that she could be mine?  \r\nShe's just my kind of girl, without her I'm blue  \r\nAnd if she ever leaves me what could I do, what could I do?\r\n\r\n"

In [16]:
df = df.sample(5000)

Text cleaning / Text Preprocessing

In [19]:
df['text'] = df['text'].str.lower().replace(r'^\w\s', ' ').replace(r'\n', ' ', regex = True)

In [20]:
df.tail(5)

,artist,song,text
7099,Gordon Lightfoot,I'll Do Anything,down in the warm dark part of my heart you sta...
37972,John Denver,Claudette,"oh, oh claudette \r oh, oh claudette \r \r..."
2129,Cake,Ruby Don't Take Your Love To Town,"you've painted up your lips and rolled, and cu..."
36180,Hooverphonic,This Strange Effect,[chorus: x2] \r you've got this strange effec...
26543,Bruce Springsteen,Born In The U. S. A.,born down in a dead mans town \r the first ki...

In [21]:
import nltk
from nltk.stem.porter import PorterStemmer

In [22]:
stemmer = PorterStemmer()

In [26]:
def token(txt) :
    token = nltk.word_tokenize(txt)
    a = [stemmer.stem(w) for w in  token]
    return " ".join(a)

In [27]:
token("You are beautiful, beauty")

'you are beauti , beauti'

In [33]:
df['text'].apply(lambda x : token(x))

17033    my hous is no mansion but it still hold my tre...
40633    close your eye and take a look at your life do...
10102    just look at your father and you 'll see how y...
24911    if i walk like a fool , i 've walk like that s...
37671    i rememb last christma eve someth happen that ...
                               ...
7099     down in the warm dark part of my heart you sta...
37972    oh , oh claudett oh , oh claudett i got a bran...
2129     you 've paint up your lip and roll , and curl ...
36180    [ choru : x2 ] you 've got thi strang effect o...
26543    born down in a dead man town the first kick i ...
Name: text, Length: 5000, dtype: object

In [34]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [35]:
tfid = TfidfVectorizer(analyzer='word', stop_words='english')

In [37]:
matrix = tfid.fit_transform(df['text'])

In [ ]:
cosine_similarity(m)